version: "3.8"
services:
  ical-api:
    image: ghcr.io/loan-mgt/cpe-calendar:latest
    container_name: ical-api
    ports:
      - 8100:8080
    environment:
      - MYCPE_USERNAME=${MYCPE_USERNAME}
      - MYCPE_PASSWORD=${MYCPE_PASSWORD}
      - START_TIMESTAMP=${START_TIMESTAMP}
      - END_TIMESTAMP=${END_TIMESTAMP}
      - SEPARATOR=${SEPARATOR}

  ical-nginx:
    image: ghcr.io/loan-mgt/10m-caching:latest
    container_name: ical-nginx
    ports:
      - 80:80
    depends_on:
      - ical-api
    environment:
      - API_HOST=ical-api:8080