version: "3.8"
services:
  ical-api:
    image: ghcr.io/loan-mgt/cpe-calendar:latest
    container_name: ical-api
    ports:
      - 8100:8080
    environment:
      - START_TIMESTAMP=${START_TIMESTAMP}
      - END_TIMESTAMP=${END_TIMESTAMP}
      - SEPARATOR=${SEPARATOR}
    volumes:
      - api-secrets:/root/secret

  ical-nginx:
    image: ghcr.io/loan-mgt/10m-caching:latest
    container_name: ical-nginx
    ports:
      - 80:80
    depends_on:
      - ical-api
    environment:
      - API_HOST=ical-api:8080
volumes:
  api-secrets: