services:
  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - MYCPE_USERNAME=${MYCPE_USERNAME}
      - MYCPE_PASSWORD=${MYCPE_PASSWORD}

  nginx:
    image: ghcr.io/loan-mgt/10m-caching:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - API_HOST=api:8080  # Pass the API host and port as an environment variable
