services:
  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - START_TIMESTAMP=${START_TIMESTAMP}
      - END_TIMESTAMP=${END_TIMESTAMP}
      - SEPARATOR=${SEPARATOR}
    volumes:
      - api-secrets:/root/secret

  nginx:
    image: ghcr.io/loan-mgt/10m-caching:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - API_HOST=api:8080  
      
volumes:
  api-secrets: